name: 'dbt_course_practice'

# Этот параметр указывает, какой профиль dbt использует для этого проекта.
profile: 'dbt_course_practice'  # имя профиля должно совпадать с файлом profiles.yml

# Эти конфигурации указывают, где dbt должен искать разные типы файлов.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:         # директории, которые будут удалены командой `dbt clean`
  - "target"
  - "dbt_packages"

# Конфигурирование моделей
# Полная документация: https://docs.getdbt.com/docs/configuring-models
